set tabstop=4
set shiftwidth=4
set expandtab
set smarttab
set backspace=2
set autoindent
set textwidth=120
set ruler
set number
inoremap jk <ESC>
execute pathogen#infect()
filetype plugin indent on
syntax on
